### ISSUE TITLE
Reference server: Fix the peer channel SQL

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-reference-server#23]
The current SQL in the peer channel code is postgres SQL blindly copied which has not been converted to SQLite compatibility. An example of this is the "TIMESTAMP" field type. All the SQL should be gone over and verified to be recognised/directly supported by SQLite.

**Comment by AustEcon** [comment]
https://github.com/electrumsv/electrumsv-reference-server/commit/10d921e7174a6aa75b91d54d5cef83b285726f56
