### ISSUE TITLE
Reference server: Remove HTTP errors from message box repository code

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-reference-server#24]
The repository code in the reference server raises an `Error` object with `status` and `reason` values. This should not be here.

![image](https://user-images.githubusercontent.com/32600614/165200860-4ff4511f-45c4-4575-8049-eeb9a34bb0d4.png)

**Comment by AustEcon** [comment]
What's your preferred methodology for propagating the details back to the client?
In this case the `write_message` database function call needs to tell the REST API handler if it was:
a) a ChannelLocked error vs 
b) a SequencingFailure error vs
c) "Failed to insert message" (because of some kind of unexpected database write failure - this was defensive code on my part rather than something I expect to ever happen)

**Comment by AustEcon** [comment]
I'm currently thinking... 

in `errors.py`:

```
class AppError(NamedTuple):
    code: int
    description: str


CHANNEL_LOCKED =               AppError(10001, "Channel is locked. Write failed.")
SEQUENCING_FAILURE =           AppError(10002, "Sequencing failure. This channel still has "
                                                "unread messages. Write failed.")
DATABASE_WRITE_FAILURE =       AppError(10003, "Database insertion failed unexpectedly - "
                                                "try again later.")
```

Then in the handler:

```
    result = msg_box_repository.write_message(message)
    if isinstance(result, AppError):
        if result in {errors.CHANNEL_LOCKED, errors.SEQUENCING_FAILURE}:
            return web.Response(reason=f"{result.code}: {result.description}",
                                status=HTTPStatus.BAD_REQUEST)
        else:
            # result == errors.DATABASE_WRITE_FAILURE
            return web.Response(reason=f"{result.code}: {result.description}",
                                status=HTTPStatus.INTERNAL_SERVER_ERROR)
```

i.e. `msg_box_repository.write_message` returns either `AppError` type or the result...

But anyways... I will try this on for size and submit some code for your review before merge.
