### ISSUE TITLE
Reference server: Re-compare peer channel implementation correctness

### ISSUE THREAD

**Issue by rt121212121** [electrumsv/electrumsv-reference-server#28]
Three set tasks:
* The `get_messages` implementation in the repository is broken and does not work for all cases, and therefore the same as the reference implementation.
* It is unclear if the peer channel timestamps in the database are UTC. I have a suspicion they are treated as local timestamps. They should be UTC timestamps.
* All the methods need to be line by line compared to the reference implementation to ensure they work the same and have the same results.

**Comment by rt121212121** [comment]
Hints for the data problems. Python `fromisoformat` does not handle random date strings. You will note that the common `Z` suffix is not parsed. It needs to be manually replaced with the `+00:00` suffix which also means UTC.

![image](https://user-images.githubusercontent.com/32600614/166636561-c9a0bc1b-4a1b-4735-b7e8-38d22f947ff7.png)

Similarly, if `isoformat` function is used, `+00:00` should be manually replaced with `Z` for consistency. Additionally, the datetime object must have a utc timezone if `isoformat` is used, or the timezone suffix will not be present. 

![image](https://user-images.githubusercontent.com/32600614/166636813-615c3dd0-c5b6-4301-8bf2-5f06843532d3.png)

![image](https://user-images.githubusercontent.com/32600614/166636855-5b6419d7-96e7-4b67-8d3a-5e45646db68b.png)

**Comment by rt121212121** [comment]
![image](https://user-images.githubusercontent.com/32600614/166637363-017db606-3ea9-4c54-9d1b-debf3270cabf.png)

**Comment by AustEcon** [comment]
One additional difference that needs correcting is the message payload is returned with base64 encoding in the PeerChannel reference implementation but is not in the ESV Reference Server.
- Will do a concurrent ESV + Reference Server updates so that nothing breaks.

**Comment by AustEcon** [comment]
Updated in: https://github.com/electrumsv/electrumsv-reference-server/commit/1e20314a18faa22b942d3cdb8023b395f2fac800
as per discussion about using timestamps in the database instead.
