### ISSUE TITLE
Direct Payment protocol: Integrate the DPP proxy into the reference server

### ISSUE THREAD

**Issue by AustEcon** [electrumsv/electrumsv-reference-server#29]
The Direct Payment Protocol proxy server ([source code](https://github.com/bitcoin-sv/dpp-proxy), [documentation](https://docs.bitcoinsv.io/liteclient-toolbox/toolbox-components/dpp-proxy)) is how we are going to support externally connectable payment of invoices in ElectrumSV. This will be integrated into the reference server in a way where both ElectrumSV users with invoices to pay, and any paying party can have their payments relayed.

This should be a production ready integration of the proxy into the reference server, using a model that external clients can connect to, to have their invoice payments routed to them.

**Comment by AustEcon** [comment]
Closing after Roger's suggestion that it's more appropriate to await these fixes by whoever is delegated the work

**Comment by rt121212121** [comment]
We run the proxy separately, no longer applicable.
